# Generated by Django 5.0.6 on 2024-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_brand_product_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, choices=[('grey', 'GREY'), ('black', 'BLACK'), ('red', 'RED'), ('blue', 'BLUE'), ('orange', 'ORANGE'), ('white', 'WHITE')], max_length=50),
        ),
    ]
